# This is a basic workflow to help you get started with Actions

name: BuildSpigot

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 
      - uses: actions/checkout@v2

      # Do the preparation
      - name: Preparing
        run: echo Hello, world!

      # Build Spigot by BuildTools
      - name: Building Spigot
        run: |
          java -jar BuildTools.jar --rev latest
          ls
      
      # Uploading the build jar files.
      - name: Uploading Build
        uses: actions/upload-artifact@v2
        with:
          name: spigot.jar
          path: ./spigot*.jar
